landing/urls.py
"""
ThunderSite - ThundeRatz

Landing Page URL patterns
Daniel Nery Silva de Oliveira

01/2018
"""

from django.urls import path
from landing import views

app_name = "landing"

urlpatterns = [
  path("", views.IndexView.as_view(), name="index"),
  path("processo-seletivo/", views.RecruitmentView.as_view(), name="recruitment")]

members/urls.py
"""
ThunderSite - ThundeRatz

Members Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "members"

urlpatterns = [path("", views.MemberListView.as_view(), name="members_list")]

news/urls.py
"""
ThunderSite - ThundeRatz

News Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="news_list"),
    path("<slug:slug>", views.NewsDetailView.as_view(), name="news_detail"),
]

projects/urls.py
"""
ThunderSite - ThundeRatz

Projects Pages URL patterns
Daniel Nery Silva de Oliveira

01/2018
"""

from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = "projects"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("projects:robots"))),
    path("robots/", views.ProjectListView.as_view(), name="robots"),
    path("robots/<slug:slug>", views.ProjectDetailView.as_view(), name="robot_detail"),
    path("boards/", views.BoardListView.as_view(), name="boards"),
    path("boards/<slug:slug>", views.BoardDetailView.as_view(), name="board_detail"),
]

thundersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import render


def forb(request):
    return render(request, "403_login.html")


urlpatterns = [
    path("", include("landing.urls")),
    path("projects/", include("projects.urls")),
    path("news/", include("news.urls")),
    path("members/", include("members.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("403/", forb),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
"""
ThunderSite - ThundeRatz

Landing Page models
Daniel Nery Silva de Oliveira

01/2018
"""

from django.db import models
from ckeditor.fields import RichTextField

## Sponsors
class Quota(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    name = models.CharField(max_length=128, unique=True)
    website = models.URLField(unique=True)
    quota = models.ForeignKey(Quota, on_delete=models.PROTECT)
    logo = models.ImageField(upload_to="sponsors")

    def __str__(self):
        return self.name


## Timeline events
class Event(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateField(unique=True)
    text = RichTextField()
    image = models.ImageField(upload_to="events")

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return self.title


## About texts
class About(models.Model):
    CHOICES = (("A", "Team"), ("B", "Workshop"))

    type = models.CharField(max_length=1, choices=CHOICES, unique=True)
    text = RichTextField()
    title = models.CharField(max_length=32)

    image1 = models.ImageField(upload_to="about")
    image2 = models.ImageField(upload_to="about")
    image3 = models.ImageField(upload_to="about")

    def __str__(self):
        return self.title


class Recruitment(models.Model):
    title = models.CharField(max_length=64)
    button = models.TextField(help_text="Cole o script do Typeform aqui", default="")
    image = models.ImageField(upload_to="ps")
    isOpen = models.BooleanField(default=False)
    info = RichTextField()

    def __str__(self):
        return self.title


class ProgressBar(models.Model):
    name = models.CharField(max_length=64)
    current_value = models.IntegerField()
    maximum_value = models.IntegerField()
    pix_link = models.URLField(default="")
    description = RichTextField(null=True, blank=True)

    def __str__(self):
        return f"Name: {self.name} {self.current_value}/{self.maximum_value}"

landing/views.py
"""
ThunderSite - ThundeRatz

Landing Page view
Daniel Nery Silva de Oliveira

01/2018
"""

from django.shortcuts import render
from django.views.generic import View, TemplateView, DetailView
from .models import Event, Sponsor, About, Recruitment, ProgressBar
from news.models import News


class IndexView(TemplateView):
    template_name = "landing/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["sponsors"] = Sponsor.objects.all()
        context["events"] = Event.objects.all()
        context["news"] = News.objects.all()[:3]
        context["the_team"] = About.objects.get(type="A")
        context["workshop"] = About.objects.get(type="B")
        context["thunder_donations"] = ProgressBar.objects.get(name="thunder_donations")

        return context


class RecruitmentView(TemplateView):
    template_name = "landing/recruitment.html"

    def get_context_data(self, **kwargs):
        context = super(RecruitmentView, self).get_context_data(**kwargs)
        context["recruitment"] = Recruitment.objects.all()[0]

        return context

landing/templates/landing/base.html
{% extends 'generic/base.html' %}

{% load staticfiles %}

{% block title_block %} ThundeRatz {% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'landing/css/jquery.fullPage.css' %}">
<link rel="stylesheet" type="text/x-sass" href="{% static 'landing/.scss/landing.scss' %}">
{% endblock %}

{% block extra_js %}
<script src="{% static 'landing/js/vivus.min.js' %}"></script>
<script src="{% static 'landing/js/jquery.fullPage.js' %}"></script>
<script src="{% static 'landing/js/timeline.js' %}"></script>

<script src="{% static 'landing/js/landing.js' %}"></script>
{% endblock %}

landing/templates/landing/index.html
{% extends 'landing/base.html' %}

{% load staticfiles %}

{% block body_block %}
    <nav id="header" class="navbar navbar-expand-lg navbar-fixed-top navbar-light">
        <img class="navbar-brand" src="{% static 'landing/img/logo.svg' %}" height="40px">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="color: yellow">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-nav ml-auto">
                <a id="menu2" class="nav-item nav-link">Not&iacute;cias</a>
                <a id="menu3" class="nav-item nav-link">A Equipe</a>
                <a id="menu4" class="nav-item nav-link">Projetos</a>
                <a id="menu5" class="nav-item nav-link">ThunderDoações</a>
                <a id="menu6" class="nav-item nav-link">Patrocinadores</a>
                <a id="menu7" class="nav-item nav-link">Contato</a>
            </div>
        </div>
    </nav>

    <div id="fullpage">

        <section class="section text-center" id="section-home">
            {% include 'landing/section_home.html' %}
        </section>

        <section class="section text-center" id="section-lastnews">
            {% include 'landing/section_lastnews.html' %}
        </section>

        <section class="section fp-auto-height-responsive" id="section-team">
            <section class="slide" id="section-about">
                {% include 'landing/section_about.html' %}
            </section>

            <section class="slide" id="section-workshop">
                {% include 'landing/section_workshop.html' %}
            </section>

            {% comment %} <section class="slide" id="section-timeline">
                {% include 'landing/section_timeline.html' %}
            </section> {% endcomment %}
        </section>

        <section class="section text-center" id="section-projects">
            {% include 'landing/section_projects.html' %}
        </section>

        <section class="section text-center" id="section-adt">
            {% include 'landing/section_adt.html' %}
        </section>

        <section class="section text-center" id="section-sponsors">
            {% include 'landing/section_sponsors.html' %}
        </section>

        <footer class="section fp-auto-height">
            {% include 'generic/footer.html' %}
        </footer>
    </div>
{% endblock %}

landing/templates/landing/recruitment.html
{% extends 'generic/base.html' %}

{% load staticfiles %}

{% block title_block %} ThundeRatz | Processo Seletivo {% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/x-sass" href="{% static 'landing/.scss/recruitment.scss' %}">
{% endblock %}

{% load  staticfiles %}

{% block body_block %}
<section id="ps-body" class="container-fluid px-0">
    <div class="top view hm-black-light">
        <div class="top-image" style="background-image: url({% static 'landing/img/equipe.jpg' %});"></div>
        <div class="mask waves-effect waves-light">
        </div>
    </div>

    <div class="container content z-depth-4 mx-auto px-1 px-md-4 px-lg-5">
        <nav id="header" class="navbar navbar-expand-md navbar-dark">
            <a href="{% url 'landing:index' %}"><img class="navbar-brand" src="{% static 'landing/img/logo.svg' %}" height="40px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul id="categories-menu" class="navbar-nav ml-auto">
                        <a href="{% url 'landing:index' %}" class="nav-link nav-item nav-special">P&aacute;gina Inicial</a>
                        <a href="{% url 'news:news_list' %}" class="nav-link nav-item nav-special">Notícias</a>
                        <a href="{% url 'projects:robots' %}" class="nav-link nav-item nav-special">Projetos</a>
                        <a href="{% url 'members:members_list' %}" class="nav-link nav-item nav-special">Membros</a>
                </ul>
            </div>
        </nav>

        <h1 text="Processo Seletivo"></h1>
        
        <div class="pt-3 pb-2">
            <h1 class="h1-responsive"><strong>Processo Seletivo</strong></h1>
            <hr>
            
            <div class="text-center">
              <img class="img-fluid center-block" src="{{ recruitment.image.url }}">
            </div>
            <div class="container" style='margin-top:25px'>
                {% if recruitment.isOpen %}
                    <div class="text-center"> {{ recruitment.button | safe }} </div>
                {% endif %}
            </div>
            <hr>
            <div class="text-justify"> {{ recruitment.info | safe }} </div>
        </div>
    </div>

    {% include 'generic/footer.html' %}
</section>

{% endblock %}

landing/templates/landing/section_about.html
{% load staticfiles %}

<div class="container-fluid p-0 row no-gutters mx-auto h-100">
    <div class="col-12 col-md-5">
        <div id="about-carousel" class="carousel carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#about-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#about-carousel" data-slide-to="1"></li>
                <li data-target="#about-carousel" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ the_team.image1.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ the_team.image2.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ the_team.image3.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
            </div>

            <a class="carousel-control-prev" href="#about-carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#about-carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="description col-12 col-md-7 px-3 pr-md-5 text-justify d-flex flex-column justify-content-center align-items-center">
        <div>
            <h1>{{ the_team.title }}</h1>
            {{ the_team.text | safe }}
        </div>
        <div class="btn-container row w-100 px-3 px-md-0">
            <div class="">
                <a href="{% url 'members:members_list' %}"><button class="btn">Membros</button></a>
            </div>
            <div class="">
                <button id="workshop-btn" class="btn">Oficina</button>
            </div>
        </div>
    </div>
</div>

landing/templates/landing/section_adt.html
{% load staticfiles %}

<div id="adt" class="">
    <div class="row no-gutters justify-content-end">
        <div id="adt-buttons" class="d-flex flex-column col-12 col-md-7 order-2 order-md-1 justify-content-center">
            <div id="doacoes" class="d-flex flex-column text-center justify-content-center">
                <div>
                    <img class="mx-auto img-fluid" src="{% static 'landing/img/thor_joinha.png' %}" alt="">
                </div>
                <div>
                    <img class="mx-auto img-fluid" src="{% static 'landing/img/thunder_longe.png' %}" alt="">
                </div>
            </div>
            <div id="doacoes-any" class="d-flex flex-column text-center justify-content-center">
                <a href="{{ thunder_donations.pix_link }}" target="_blank" id="doe1">
                    <div style="font-weight: 500;">Contribua com qualquer valor!</div>
                    <div style="font-size: 1.5rem;">
                        clicando aqui: <img src="{% static 'landing/img/pix-logo.png' %}" class="col-6 col-md-2" alt="">
                    </div>
                </a>
            </div>
            <div id="doacoes-imgs" class="">
                <!-- GIFzão -->
                <img class="img-fluid" src="{% static 'landing/img/thor_coin.gif' %}" alt="">
            </div>
        </div>
        <div id="adt-info"
            class="d-flex flex-column justify-content-around col-12 col-md-5 order-1 order-md-2 pr-0 pr-md-5">
            <div id="adt-logo">
                <img src="{% static 'landing/img/logo_adt.png' %}" alt="" class="img-fluid">
            </div>
            <div id="adt-progress" class="container">
                <div id="adt-meta" class="d-flex flex-column text-center justify-content-center">
                    Meta: R$ {{thunder_donations.maximum_value}},00 <br>
                    Arrecadado: R$ {{thunder_donations.current_value}},00
                </div>
                <progress id="progress-bar" class="col-12 col-md-10" value="{{thunder_donations.current_value}}"
                    max="{{thunder_donations.maximum_value}}"> </progress>
            </div>
            <div id="adt-description" class="d-flex flex-column text-center justify-content-center">
                {{ thunder_donations.description | safe }}
            </div>
        </div>
    </div>
</div>

landing/templates/landing/section_lastnews.html
{% load staticfiles %}

<div class="last-news-and-button">
    <h2 class="h2-responsive title">&Uacute;ltimas not&iacute;cias!</h2>
    <a href="{% url 'news:news_list' %}"<button id="news-btn" class="btn">Ver todas <i class="fas fa-newspaper"></i></button></a>
</div>
{% for new in news %}
<div class="slide" style="background-image: url({{ new.cover_image.url }})">
    <a href="{% url 'news:news_detail' new.slug %}">
        <div class="title-wrapper d-flex flex-column">
            <h1 class="h1-responsive mt-auto title">{{ new.title }}</h1>
        </div>
    </a>
</div>
{% endfor %}

landing/templates/landing/section_projects.html
{% load staticfiles %}

<div id="projects-index">
    <div class="row no-gutters justify-content-end">
        <a id="card-robots" class="col-12 col-md-6" href="{% url 'projects:robots' %}">
            <h3 class="d-flex flex-column flex-nowrap justify-content-center">Rob&ocirc;s</h3>
        </a>
        <a id="card-boards" class="col-12 col-md-6" href="{% url 'projects:boards' %}">
            <h3 class="d-flex flex-column flex-nowrap justify-content-center">Eletr&ocirc;nicas</h3>
        </a>
    </div>
</div>

landing/templates/landing/section_sponsors.html
{% load staticfiles %}

<div id="sponsors" class="d-flex flex-column flex-nowrap justify-content-end">
    <div><h1 class="h1-responsive mt-5 mb-0">Patrocinadores</h1></div>
    <div id="sponsors-gold-w1" class="d-flex flex-column flex-nowrap justify-content-center">
        <div id="sponsors-gold-w2">
            {% for sponsor in sponsors %}
                {% if sponsor.quota.name == 'Ouro' %}
                <div>
                    <a target="_blank" href="{{ sponsor.website }}"><div style="background-image: url({{ sponsor.logo.url }})"></div></a>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div id="sponsors-silver-w1" class="d-flex flex-column flex-nowrap justify-content-center">
        <div id="sponsors-silver-w2">
            {% for sponsor in sponsors %}
                {% if sponsor.quota.name == 'Prata' %}
                <div>
                    <a target="_blank" href="{{ sponsor.website }}"><div style="background-image: url({{ sponsor.logo.url }})"></div></a>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div id="sponsors-bronze-w1" class="d-flex flex-column flex-nowrap justify-content-center">
        <div id="sponsors-bronze-w2">
            {% for sponsor in sponsors %}
                {% if sponsor.quota.name == 'Bronze' %}
                <div>
                    <a target="_blank" href="{{ sponsor.website }}"><div style="background-image: url({{ sponsor.logo.url }})"></div></a>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

landing/templates/landing/section_timeline.html
{% load staticfiles %}

<div class="cd-horizontal-timeline h-100 d-flex flex-column justify-content-center">
    <div class="timeline">
        <div class="events-wrapper">
            <div class="events">
                <ol>
                    {% for e in events %}
                    <li><a href="#0" data-date="{{ e.date | date:'d/m/Y' }}" {% if forloop.first %}class="selected"{% endif %}>{{ e.date | date:'d M'}}</a></li>
                    {% endfor %}
                </ol>

                <span class="filling-line" aria-hidden="true"></span>
            </div> <!-- .events -->
        </div> <!-- .events-wrapper -->

        <ul class="cd-timeline-navigation">
            <li><a href="#0" class="prev inactive">Prev</a></li>
            <li><a href="#0" class="next">Next</a></li>
        </ul> <!-- .cd-timeline-navigation -->
    </div> <!-- .timeline -->

    <div class="events-content">
        <ol>
            {% for e in events %}
            <li {% if forloop.first %}class="selected"{% endif %} data-date="{{ e.date | date:'d/m/Y' }}">
                <div class="event-image" style="background-image: url({{ e.image.url }})"></div>
                <div>
                    <h2>{{ e.title }}</h2>
                    <em>{{ e.date | date }}</em>
                    {{ e.text | safe }}
                </div>
            </li>
            {% endfor %}
        </ol>
    </div> <!-- .events-content -->
</div>

landing/templates/landing/section_workshop.html
{% load staticfiles %}

<div class="container-fluid p-0 row no-gutters mx-auto h-100">
    <div class="description col-12 order-2 col-md-7 order-md-1 px-3 pl-md-5 text-justify d-flex flex-column justify-content-center align-items-center">
        <div>
            <h1>{{ workshop.title }}</h1>
            {{ workshop.text | safe }}
        </div>
        <div class="btn-container row w-100 px-3 px-md-0">
            <div class="">
                <a href="{% url 'members:members_list' %}"><button class="btn">Membros</button></a>
            </div>
            <div class="">
                <button id="team-btn" class="btn">Equipe</button>
            </div>
        </div>
    </div>
    <div class="col-12 order-1 col-md-5 order-md-2">
        <div id="workshop-carousel" class="carousel carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#workshop-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#workshop-carousel" data-slide-to="1"></li>
                <li data-target="#workshop-carousel" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ workshop.image1.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ workshop.image2.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="view hm-black-slight">
                        <div class="d-block w-100 carousel-img-div" style="background-image: url({{ workshop.image3.url }})"></div>
                        <div class="mask"></div>
                    </div>
                </div>
            </div>

            <a class="carousel-control-prev" href="#workshop-carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#workshop-carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>