landing/urls.py
"""
ThunderSite - ThundeRatz

Landing Page URL patterns
Daniel Nery Silva de Oliveira

01/2018
"""

from django.urls import path
from landing import views

app_name = "landing"

urlpatterns = [
  path("", views.IndexView.as_view(), name="index"),
  path("processo-seletivo/", views.RecruitmentView.as_view(), name="recruitment")]

members/urls.py
"""
ThunderSite - ThundeRatz

Members Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "members"

urlpatterns = [path("", views.MemberListView.as_view(), name="members_list")]

news/urls.py
"""
ThunderSite - ThundeRatz

News Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="news_list"),
    path("<slug:slug>", views.NewsDetailView.as_view(), name="news_detail"),
]

thundersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import render


def forb(request):
    return render(request, "403_login.html")


urlpatterns = [
    path("", include("landing.urls")),
    path("projects/", include("projects.urls")),
    path("news/", include("news.urls")),
    path("members/", include("members.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("403/", forb),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/models.py
"""
ThunderSite - ThundeRatz

Members Models
Daniel Nery Silva de Oliveira

02/2018
"""

from django.db import models
from django.core.exceptions import ValidationError


def member_picture_path(instance, filename):
    ext = filename.split(".")[-1]
    return "members/" + instance.nickname + "." + ext


class Member(models.Model):
    CHOICES = (
        ("EL", "Elétrica"),
        ("MC", "Mecânica"),
        ("CP", "Computação"),
        ("DM", "Design e Marketing"),
        ("AF", "Administrativo e Financeiro"),
    )

    name = models.CharField(max_length=128)
    nickname = models.CharField(max_length=64, unique=True)
    area = models.CharField(max_length=2, choices=CHOICES)
    area_captain = models.BooleanField(default=False)
    team_captain = models.BooleanField(default=False)
    picture = models.ImageField(upload_to=member_picture_path, default="1000x1000.png")
    facebook = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    email = models.EmailField()
    entry_year = models.PositiveSmallIntegerField()

    class Meta:
        ordering = ["-team_captain", "-area_captain", "name"]

    def __str__(self):
        return self.name

    def clean(self):
        if self.area_captain is True and self.team_captain is True:
            raise ValidationError(
                {
                    "area_captain": ValidationError("Choose only one!", code="invalid"),
                    "team_captain": ValidationError("Choose only one!", code="invalid"),
                }
            )
        if self.area_captain is True and self.area == "AF":
            raise ValidationError(
                {
                    "area_captain": ValidationError(
                        "This area doesn't have captains!", code="invalid"
                    )
                }
            )

members/views.py
"""
ThunderSite - ThundeRatz

Members Pages Views
Daniel Nery Silva de Oliveira

02/2018
"""

from django.views.generic import ListView
from .models import Member


class MemberListView(ListView):
    model = Member
    context_object_name = "members_list"
    template_name = "members/members_list.html"

members/templates/members/members_base.html
{% extends 'generic/base.html' %}

{% load staticfiles %}

{% block extra_css %}
<link rel="stylesheet" type="text/x-sass" href="{% static 'members/.scss/members.scss' %}">
{% endblock %}

{% block body_block %}
<section id="members-body" class="container-fluid px-0">
    <div class="top view hm-black-strong">
        <div class="top-image" style="background-image: url({% block top_image_block %}{% endblock %});"></div>
        <div class="mask waves-effect waves-light">
            {% block top_title_block %}{% endblock %}
        </div>
    </div>

    <div class="content z-depth-4 mx-1 mx-md-4 mx-lg-5">
        <nav id="header" class="navbar navbar-expand-md navbar-dark">
            <a href="{% url 'landing:index' %}"><img class="navbar-brand" src="{% static 'landing/img/logo.svg' %}" height="40px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% block nav_block %}
                    {% endblock %}
                </ul>
            </div>
        </nav>

        {% block content_block %}
        {% endblock %}

    </div>

    {% include "generic/footer.html" %}
</section>
{% endblock %}

{% block extra_js %}
<script src="{% static 'generic/js/jquery.lazy.min.js' %}"></script>
<script src="{% static 'members/js/members.js' %}"></script>
{% endblock %}

members/templates/members/members_list.html
{% extends 'members/members_base.html' %}
{% load staticfiles %}

{% block title_block %}ThundeRatz | Membros{% endblock %}

{% block top_image_block %}{% static 'members/img/cover.jpg' %}{% endblock %}
{% block top_title_block %}<h1 class="title white-text">Membros</h1>{% endblock %}

{% block nav_block %}
<li class="nav-item">
    <a href="{% url 'landing:index' %}" class="nav-special nav-link">Início</a>
</li>
<li class="nav-item">
    <a href="{% url 'news:news_list' %}" class="nav-special nav-link">Notícias</a>
</li>
<li class="nav-item">
    <a href="{% url 'projects:robots' %}" class="nav-special nav-link">Projetos</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="areasMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Áreas
    </a>
    <div id="areas-menu" class="dropdown-menu dropdown-menu-right" aria-labelledby="areasMenu">
        <a class="dropdown-item" data-area='EL'><i class="fas fa-bolt"></i> Elétrica</a>
        <a class="dropdown-item" data-area='MC'><i class="fas fa-cogs"></i> Mecânica</a>
        <a class="dropdown-item" data-area='CP'><i class="fas fa-code"></i> Computação</a>
        <a class="dropdown-item" data-area='DM'><i class="fas fa-paint-brush"></i> Design e Marketing</a>
        <a class="dropdown-item" data-area='AF'><i class="fas fa-handshake"></i> Administrativo e Financeiro</a>
        <a class="dropdown-item" data-area='all'>Todas</a>
    </div>
</li>
{% endblock %}

{% block content_block %}

<div id="member-row" class="row">
    {% for member in members_list %}
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xxl-2" data-area="{{ member.area }}">
        <div class="card card-body text-center mx-2 my-2">
            <div class="member-photo mx-auto my-3" data-src="{{ member.picture.url }}">
            {% comment %} <div class="member-photo mx-auto my-3" style="background-image: url({{ member.picture.url }})"> {% endcomment %}
                <div class="area-badge
                    {% if member.team_captain %}
                    tcap
                    {% elif member.area_captain %}
                    acap
                    {% endif %}
                    ">
                    {% if member.team_captain %}
                    <i class="fas fa-copyright fa-2x"></i>
                    {% elif member.area == 'EL' %}
                    <i class="fas fa-bolt fa-2x"></i>
                    {% elif member.area == 'MC' %}
                    <i class="fas fa-cogs fa-2x"></i>
                    {% elif member.area == 'CP' %}
                    <i class="fas fa-code fa-2x"></i>
                    {% elif member.area == 'DM' %}
                    <i class="fas fa-paint-brush fa-2x"></i>
                    {% elif member.area == 'AF' %}
                    <i class="fas fa-handshake fa-2x"></i>
                    {% endif %}
                </div>
            </div>
            <h3 class="h3-responsive font-bold">{{ member.nickname }}</h3>
            <p class="text-muted mb-0">{{ member.name }}</h2>
            <div class="card-hover card-body w-100 h-100 d-flex flex-column">
                <h3 class="h3-responsive font-bold">{{ member.nickname }}</h3>
                <p class="text-muted mb-0">{{ member.name }}</h2>
                <p>Ano de Ingresso: {{ member.entry_year }}</p>
                <p>
                    {% if member.area == 'EL' %}
                    <i class="fas fa-bolt"></i>
                    {% elif member.area == 'MC' %}
                    <i class="fas fa-cogs"></i>
                    {% elif member.area == 'CP' %}
                    <i class="fas fa-code"></i>
                    {% elif member.area == 'DM' %}
                    <i class="fas fa-paint-brush"></i>
                    {% elif member.area == 'AF' %}
                    <i class="fas fa-handshake"></i>
                    {% endif %}
                    {{ member.get_area_display }}
                </p>
                {% if member.team_captain %}
                <strong>Capitão Geral</strong>
                {% endif %}
                {% if member.area_captain %}
                <em>Capitã(o) de Área</em>
                {% endif %}
                <div class="social d-flex flex-row mt-auto">
                    {% if member.facebook %}
                    <a href="{{ member.facebook }}" class="mr-2"><i class="fab fa-facebook fa-2x"></i></a>
                    {% endif %}
                    {% if member.email %}
                    <a href="mailto:{{ member.email }}"  class="mr-2"><i class="fas fa-envelope fa-2x"></i></a>
                    {% endif %}
                    {% if member.github %}
                    <a href="{{ member.github }}"><i class="fab fa-github fa-2x"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}