landing/urls.py
"""
ThunderSite - ThundeRatz

Landing Page URL patterns
Daniel Nery Silva de Oliveira

01/2018
"""

from django.urls import path
from landing import views

app_name = "landing"

urlpatterns = [
  path("", views.IndexView.as_view(), name="index"),
  path("processo-seletivo/", views.RecruitmentView.as_view(), name="recruitment")]

members/urls.py
"""
ThunderSite - ThundeRatz

Members Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "members"

urlpatterns = [path("", views.MemberListView.as_view(), name="members_list")]

news/urls.py
"""
ThunderSite - ThundeRatz

News Pages URL patterns
Daniel Nery Silva de Oliveira

02/2018
"""

from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="news_list"),
    path("<slug:slug>", views.NewsDetailView.as_view(), name="news_detail"),
]

projects/urls.py
"""
ThunderSite - ThundeRatz

Projects Pages URL patterns
Daniel Nery Silva de Oliveira

01/2018
"""

from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = "projects"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("projects:robots"))),
    path("robots/", views.ProjectListView.as_view(), name="robots"),
    path("robots/<slug:slug>", views.ProjectDetailView.as_view(), name="robot_detail"),
    path("boards/", views.BoardListView.as_view(), name="boards"),
    path("boards/<slug:slug>", views.BoardDetailView.as_view(), name="board_detail"),
]

thundersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import render


def forb(request):
    return render(request, "403_login.html")


urlpatterns = [
    path("", include("landing.urls")),
    path("projects/", include("projects.urls")),
    path("news/", include("news.urls")),
    path("members/", include("members.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("403/", forb),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
"""
ThunderSite - ThundeRatz

Projects Models
Daniel Nery Silva de Oliveira

01/2018
"""

from django.db import models
from ckeditor.fields import RichTextField
from members.models import Member

## Boards
def board_thumbnail_path(instance, filename):
    pass


def board_cover_path(instance, filename):
    return "projects/" + instance.slug + "/cover_" + filename


def board_card_path(instance, filename):
    return "projects/" + instance.slug + "/card_" + filename


class Board(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(
        unique=True,
        help_text="URL name: <em>thunderatz.org/projects/boards/&lt;slug&gt;</em>",
    )
    cover_image = models.ImageField(upload_to=board_cover_path, default="1000x1000.png")
    card_image = models.ImageField(upload_to=board_card_path, default="1000x1000.png")
    description = RichTextField()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


def board_images_path(instance, filename):
    return "projects/" + instance.board.name + "/" + filename


class BoardImage(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name="pictures")
    image = models.ImageField(upload_to=board_images_path)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.description


## Projects
class SuperCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "super categories"


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=512)
    super_category = models.ForeignKey(SuperCategory, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"


def project_cover_path(instance, filename):
    return "projects/" + instance.slug + "/cover_" + filename


def project_card_path(instance, filename):
    return "projects/" + instance.slug + "/card_" + filename


class Project(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(
        unique=True,
        help_text="URL name: <em>thunderatz.org/projects/robots/&lt;slug&gt;</em>",
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    logo = models.ImageField(upload_to="project_logos", default="1000x1000.png")
    typography = models.ImageField(
        upload_to="project_typography", default="1000x1000.png"
    )
    cover_image = models.ImageField(
        upload_to=project_cover_path, default="1000x1000.png"
    )
    card_image = models.ImageField(upload_to=project_card_path, default="1000x1000.png")

    debut_year = models.PositiveSmallIntegerField()

    gold = models.PositiveSmallIntegerField(default=0)
    silver = models.PositiveSmallIntegerField(default=0)
    bronze = models.PositiveSmallIntegerField(default=0)

    description = RichTextField()
    is_active = models.BooleanField(default=True)
    boards = models.ManyToManyField(Board, blank=True, related_name="projects")
    bold = models.ForeignKey(Member, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ["-is_active", "-debut_year", "name"]

    def __str__(self):
        return self.name


def project_images_path(instance, filename):
    return "projects/" + instance.project.name + "/" + filename


class ProjectImage(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="pictures"
    )
    image = models.ImageField(upload_to=project_images_path)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.description

projects/views.py
"""
ThunderSite - ThundeRatz

Projects Pages Views
Daniel Nery Silva de Oliveira

01/2018
"""

from django.shortcuts import render, get_object_or_404
from django.views.generic import View, TemplateView, ListView, DetailView
from .models import Project, Board

# Create your views here.
class ProjectListView(ListView):
    template_name = "projects/projects_list.html"
    model = Project
    context_object_name = "project_list"


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    context_object_name = "project"


class BoardListView(ListView):
    model = Board
    template_name = "projects/boards_list.html"
    context_object_name = "board_list"


class BoardDetailView(DetailView):
    model = Board
    template_name = "projects/board_detail.html"
    context_object_name = "board"

projects/templates/projects/base.html
<!DOCTYPE html>

{% load compress %}
{% load staticfiles %}

<html lang="pt">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title_block %}{% endblock %}</title>

        {% compress js %}
        <script src="{% static 'landing/js/fontawesome-all.js' %}"></script>
        <script src="{% static 'landing/js/jquery-3.2.1.js' %}"></script>
        {% endcompress %}

        <link href="https://fonts.googleapis.com/css?family=Fira+Sans|Lato" rel="stylesheet">

        {% compress css %}
        <link rel="stylesheet" href="{% static 'generic/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'generic/css/mdb.css' %}">
        <link rel="stylesheet" href="{% static 'landing/css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'generic/css/slick-theme.css' %}">
        <link rel="stylesheet" href="{% static 'projects/css/lightbox.css' %}">

        <link rel="stylesheet" type="text/x-sass" href="{% static 'generic/.scss/thundersite.scss' %}">
        <link rel="stylesheet" type="text/x-sass" href="{% static 'projects/.scss/projects.scss' %}">
        {% endcompress %}
    </head>
    <body class="custom-scroll">
        {% block body_block %}
        {% endblock %}

        {% compress js %}
        <script src="{% static 'generic/js/popper.min.js' %}"></script>
        <script src="{% static 'generic/js/bootstrap.js' %}"></script>
        <script src="{% static 'generic/js/mdb.js' %}"></script>
        <script src="{% static 'landing/js/slick.min.js' %}"></script>
        <script src="{% static 'projects/js/lightbox.js' %}"></script>

        <script src="{% static 'projects/js/projects.js' %}"></script>
        {% endcompress %}
    </body>
</html>

projects/templates/projects/board_detail.html
{% extends 'projects/projects_base.html' %}
{% load staticfiles %}

{% block title_block %}ThundeRatz | {{ board.name }}{% endblock %}

{% block top_image_block %}{% static 'landing/img/micropress.jpg' %}{% endblock %}
{% block top_title_block %}<h1 class="title white-text">{{ board.name }}</h1>{% endblock %}

{% block nav_block %}
<a href="{% url 'landing:index' %}" class="nav-link nav-item nav-special">In&iacute;cio</a>
<a href="{% url 'projects:boards' %}"class="nav-link nav-item nav-special">Lista de Placas</a>
<a id="contact-button" class="nav-link nav-item nav-special">Contato</a>
{% endblock %}

{% block content_block %}
<div class="row">
    <div class="col-md-3" id="left-info-wrapper">
        <div id="left-info" class="z-depth-2 mr-3 mr-md-0 ml-3 my-3" style='background-image: url("{% static 'projects/img/background1.png' %}")'>
            <div style="background-image: url({{ board.card_image.url }})" class="thumbnail mx-auto pt-2"></div>
            <div class="card-body">
                <div class="d-flex flex-column px-2">
                    <h2 class="card-title text-center">{{ board.name }}</h4>
                    <div class="line"></div>
                    {% for project in board.projects.all %}
                    <div class="row">
                        <div class="font-bold">{% if forloop.first %}Rob&ocirc;s{% endif %}</div>
                        <div class="ml-auto"><a href="{% url 'projects:robot_detail' project.slug %}">{{ project.name }}</a></div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="d-block w-100 p-3 text-justify">
            <h1>{{ board.name }}</h1>

            <hr>

            {{ board.description | safe }}

            <hr>

            <div id="project-images-w1" class="d-flex flex-column flex-nowrap justify-content-center mx-auto">
                <div id="project-images-w2">
                    {% for pic in board.pictures.all %}
                    <div>
                        <a href="{{ pic.image.url }}" data-lightbox="project-gallery" data-title="{{ pic.description }}"><div class="image z-depth-1" style="background-image: url({{ pic.image.url }});"></div></a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
{{ block.super }}
<script src="{% static 'projects/js/boards_detail.js' %}"></script>
{% endblock %}

projects/templates/projects/boards_list.html
{% extends 'projects/projects_base.html' %}
{% load staticfiles %}

{% block title_block %}ThundeRatz | Placas{% endblock %}

{% block top_image_block %}{% static 'landing/img/micropress.jpg' %}{% endblock %}
{% block top_title_block %}<h1 class="title white-text">Eletr&ocirc;nicas</h1>{% endblock %}

{% block nav_block %}
<li class="nav-item">
    <a href="{% url 'landing:index' %}" class="nav-special nav-link">Início</a>
</li>
<li class="nav-item">
    <a href="{% url 'news:news_list' %}" class="nav-special nav-link">Notícias</a>
</li>
<li class="nav-item">
    <a href="{% url 'projects:robots' %}" class="nav-special nav-link">Rob&ocirc;s</a>
</li>
<li class="nav-item">
    <a href="{% url 'members:members_list' %}" class="nav-special nav-link">Membros</a>
</li>
{% endblock %}

{% block content_block %}
<div id="project-row" class="row">
    {% for board in board_list %}
    <div class="col-12 col-custom" data-cat="{{ project.category.super_category }}">
        <div class="card my-2 mx-2" style='background-image: url("{% static 'projects/img/background1.png' %}")'>
            <div class="card-img-top" style='background-image: url("{{ board.card_image.url }}")'></div>
            <div class="card-body">
                <div class="d-flex flex-column px-2">
                    <div class="row">
                        <div class="font-bold mx-auto"><h3 class="mb-0">{{ board.name }}</h3></div>
                    </div>
                </div>
            </div>
            <a href="{% url 'projects:board_detail' board.slug %}" class="card-overlay w-100 h-100 d-flex flex-column justify-content-center align-items-center">
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'projects/projects_base.html' %}
{% load staticfiles %}

{% block title_block %}ThundeRatz | {{ project.name }}{% endblock %}

{% block top_image_block %}{{ project.cover_image.url }}{% endblock %}
{% block top_title_block %}<img src="{{ project.typography.url }}" class="typography">{% endblock %}

{% block nav_block %}
<a href="{% url 'landing:index' %}" class="nav-link nav-item nav-special">In&iacute;cio</a>
<a href="{% url 'projects:robots' %}"class="nav-link nav-item nav-special">Lista de Projetos</a>
<a id="contact-button" class="nav-link nav-item nav-special">Contato</a>
{% endblock %}

{% block content_block %}
<div class="row">
    <div class="col-md-3" id="left-info-wrapper">
        <div id="left-info" class="z-depth-2 mr-3 mr-md-0 ml-3 my-3"
            {% if project.is_active %}
            style='background-image: url("{% static 'projects/img/background1.png' %}")'
            {% else %}
            style='background-image: url("{% static 'projects/img/background1-velhos.png' %}")'
            {% endif %}
        >
            <div style='background-image: url("{{ project.card_image.url }}")' class="thumbnail mx-auto pt-2"></div>
            <div class="card-body">
                <div class="d-flex flex-column px-2">
                    <div class="row">
                        <div class="font-bold">Categoria</div>
                        <div class="ml-auto">{{ project.category }}</div>
                    </div>
                    <div class="line"></div>
                    <div class="row">
                        <div class="font-bold">Estreia</div>
                        <div class="ml-auto">{{ project.debut_year }}</div>
                    </div>
                    <div class="line"></div>
                    {% if project.bold.nickname %}
                    <div class="row">
                        <div class="font-bold">Respons&aacute;vel</div>
                        <div class="ml-auto"><a href="{% url 'members:members_list' %}">{{ project.bold.nickname }}</a></div>
                    </div>
                    <div class="line"></div>
                    {% endif %}

                    {% for board in project.boards.all %}
                    <div class="row">
                        <div class="font-bold">{% if forloop.first %}Eletr&ocirc;nica{% endif %}</div>
                        <div class="ml-auto"><a href="{% url 'projects:board_detail' board.slug %}">{{ board.name }}</a></div>
                    </div>
                    <div class="line"></div>
                    {% endfor %}
                    <div class="row">
                        <span class="col"><i class="fas fa-trophy" style="color: gold"></i>&nbsp;&nbsp;{{ project.gold }}</span>
                        <span class="col"><i class="fas fa-trophy" style="color: silver"></i>&nbsp;&nbsp;{{ project.silver }}</span>
                        <span class="col"><i class="fas fa-trophy" style="color: brown"></i>&nbsp;&nbsp;{{ project.bronze }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="d-block w-100 p-3 text-justify">
            <h1>{{ project.name }}</h1>

            <hr>

            {{ project.description | safe }}

            <hr>

            <div id="project-images-w1" class="d-flex flex-column flex-nowrap justify-content-center mx-auto">
                <div id="project-images-w2">
                    {% for pic in project.pictures.all %}
                    <div>
                        <a href="{{ pic.image.url }}" data-lightbox="project-gallery" data-title="{{ pic.description }}"><div class="image z-depth-1" style='background-image: url("{{ pic.image.url }}");'></div></a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
{{ block.super }}
<script src="{% static 'projects/js/projects_detail.js' %}"></script>
{% endblock %}

projects/templates/projects/projects_base.html
{% extends 'generic/base.html' %}

{% load staticfiles %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'projects/css/lightbox.css' %}">
<link rel="stylesheet" type="text/x-sass" href="{% static 'projects/.scss/projects.scss' %}">
{% endblock %}

{% block body_block %}
<section id="project-body" class="container-fluid px-0">
    <div class="top view hm-black-strong">
        <div class="top-image" style='background-image: url("{% block top_image_block %}{% endblock %}");'></div>
        <div class="mask waves-effect waves-light">
            {% block top_title_block %}{% endblock %}
        </div>
    </div>

    <div class="content z-depth-4 mx-1 mx-md-4 mx-lg-5">
        <nav id="header" class="navbar navbar-expand-md navbar-dark">
            <a href="{% url 'landing:index' %}"><img class="navbar-brand" src="{% static 'landing/img/logo.svg' %}" height="40px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% block nav_block %}
                    {% endblock %}
                </ul>
            </div>
        </nav>

        {% block content_block %}
        {% endblock %}

    </div>

    {% include "generic/footer.html" %}
</section>
{% endblock %}

{% block extra_js %}
<script src="{% static 'projects/js/lightbox.js' %}"></script>
{% endblock %}

projects/templates/projects/projects_list.html
{% extends 'projects/projects_base.html' %}
{% load staticfiles %}

{% block title_block %}ThundeRatz | Robôs{% endblock %}

{% block top_image_block %}{% static 'projects/img/cover.jpeg' %}{% endblock %}
{% block top_title_block %}<h1 class="title white-text">Rob&ocirc;s</h1>{% endblock %}

{% block nav_block %}
<li class="nav-item">
    <a href="{% url 'landing:index' %}" class="nav-special nav-link">Início</a>
</li>
<li class="nav-item">
    <a href="{% url 'news:news_list' %}" class="nav-special nav-link">Notícias</a>
</li>
<li class="nav-item">
    <a href="{% url 'projects:boards' %}" class="nav-special nav-link">Eletrônicas</a>
</li>
<li class="nav-item">
    <a href="{% url 'members:members_list' %}" class="nav-special nav-link">Membros</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="catMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categorias
    </a>
    <div id="categories-menu" class="dropdown-menu dropdown-menu-right" aria-labelledby="catMenu">
        <a class="dropdown-item" data-cat='combate'>Combate</a>
        <a class="dropdown-item" data-cat='sumo'>Sumo</a>
        <a class="dropdown-item" data-cat='autonomo'>Autonomo</a>
        <a class="dropdown-item" data-cat='hockey'>Hockey</a>
        <a class="dropdown-item" data-cat='all'>Todas</a>
    </div>
</li>

{% endblock %}

{% block content_block %}
<div id="project-row" class="row">
    {% for project in project_list %}
    <div class="col-12 col-custom" data-cat="{{ project.category.super_category }}">
        <div class="card my-2 mx-2"
            {% if project.is_active %}
            style='background-image: url("{% static 'projects/img/background1.png' %}")'
            {% else %}
            style='background-image: url("{% static 'projects/img/background1-velhos.png' %}")'
            {% endif %}
        >
            <div class="card-img-top" data-src="{{ project.card_image.url|escape }}"></div>
            {% comment %} <div class="card-img-top" style='background-image: url("{{ project.card_image.url }}")'></div> {% endcomment %}
            <div class="card-body">
                <div class="d-flex flex-column px-2">
                    <div class="row">
                        <div class="font-bold">Nome</div>
                        <div class="ml-auto">{{ project.name }}</div>
                    </div>
                    <div class="line line1"></div>
                    <div class="row">
                        <div class="font-bold">Categoria</div>
                        <div class="ml-auto">{{ project.category }}</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'projects:robot_detail' project.slug %}" class="card-overlay w-100 h-100 d-flex flex-column justify-content-center align-items-center">
                <img src="{{ project.typography.url }}" alt="">
            </a>
        </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

{% block extra_js %}
{{ block.super }}
<script src="{% static 'generic/js/jquery.lazy.min.js' %}"></script>
<script src="{% static 'projects/js/projects_list.js' %}"></script>
{% endblock %}